export const patients = [
  {
    id: 1,
    vorname: 'Maria',
    nachname: 'Schmidt',
    versicherungsnr: 'V-2024-001',
    klinikum: 'Klinikum Konstanz',
    status: 'Stationär',
    geburtsdatum: '15.03.1985',
    telefon: '+49 170 1234567',
    email: 'm.schmidt@email.de',
    adresse: 'Musterstr. 12, 78462 Konstanz',
    etage: '3. OG',
    abteilung: 'Kardiologie',
    station: 'Station K3',
    zimmer: '304',
    bett: 'Bett A',
    notfallkontakt: {
      name: 'Hans Schmidt',
      beziehung: 'Ehepartner',
      telefon: '+49 170 7654321',
    },
  },
  {
    id: 2,
    vorname: 'Thomas',
    nachname: 'Weber',
    versicherungsnr: 'V-2024-002',
    klinikum: 'Klinikum Konstanz',
    status: 'Stationär',
    geburtsdatum: '22.07.1972',
    telefon: '+49 171 2345678',
    email: 't.weber@email.de',
    adresse: 'Seestr. 8, 78464 Konstanz',
    etage: '2. OG',
    abteilung: 'Innere Medizin',
    station: 'Station I2',
    zimmer: '212',
    bett: 'Bett B',
    notfallkontakt: {
      name: 'Sabine Weber',
      beziehung: 'Ehepartnerin',
      telefon: '+49 171 8765432',
    },
  },
  {
    id: 3,
    vorname: 'Anna',
    nachname: 'Hoffmann',
    versicherungsnr: 'V-2024-003',
    klinikum: 'Klinikum Konstanz',
    status: 'Ambulant',
    geburtsdatum: '03.11.1990',
    telefon: '+49 172 3456789',
    email: 'a.hoffmann@email.de',
    adresse: 'Bahnhofstr. 22, 78462 Konstanz',
    etage: 'EG',
    abteilung: 'Ambulanz',
    station: '–',
    zimmer: '–',
    bett: '–',
    notfallkontakt: {
      name: 'Klaus Hoffmann',
      beziehung: 'Vater',
      telefon: '+49 172 9876543',
    },
  },
  {
    id: 4,
    vorname: 'Peter',
    nachname: 'Braun',
    versicherungsnr: 'V-2024-004',
    klinikum: 'Klinikum Konstanz',
    status: 'Stationär',
    geburtsdatum: '08.05.1965',
    telefon: '+49 173 4567890',
    email: 'p.braun@email.de',
    adresse: 'Rheinsteig 5, 78462 Konstanz',
    etage: '4. OG',
    abteilung: 'Chirurgie',
    station: 'Station C4',
    zimmer: '418',
    bett: 'Bett A',
    notfallkontakt: {
      name: 'Maria Braun',
      beziehung: 'Tochter',
      telefon: '+49 173 0987654',
    },
  },
  {
    id: 5,
    vorname: 'Lisa',
    nachname: 'Krause',
    versicherungsnr: 'V-2024-005',
    klinikum: 'Klinikum Konstanz',
    status: 'Ambulant',
    geburtsdatum: '17.09.1998',
    telefon: '+49 174 5678901',
    email: 'l.krause@email.de',
    adresse: 'Marktplatz 3, 78462 Konstanz',
    etage: 'EG',
    abteilung: 'Ambulanz',
    station: '–',
    zimmer: '–',
    bett: '–',
    notfallkontakt: {
      name: 'Julia Krause',
      beziehung: 'Schwester',
      telefon: '+49 174 1098765',
    },
  },
];
